#define LESI_D0_PIN           (0)
#define LESI_PAR_PIN          (16)
#define LESI_INIT_PIN         (18)
#define LESI_T1_PIN           (19)
#define LESI_AC_CLEAR_PIN     (20)
#define LESI_STROBE_PIN       (21)
#define LESI_CMD_PIN          (22)
#define LESI_CP_OK_PIN        (23)
#define LESI_BUF_OE_PIN       (24)
#define LESI_BUF_WRITE_PIN    (25)

//TODO: Move to nano delays
#define LESI_DELAY_TURNAROUND (3)
#define LESI_DELAY_CMD_STROBE (3)
#define LESI_DELAY_STROBE_CMD (3)
#define LESI_DELAY_CMD_END    (3)
#define LESI_DELAY_RD_STROBE  (3)
#define LESI_DELAY_WR_STROBE  (3)
#define LESI_DELAY_WR_SETUP   (3)
#define LESI_DELAY_PWRGOOD    (10)
#define LESI_DELAY_AC_CLEAR   (500)